config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :acknowledgements
  get 'welcome/index'

  resources :people
  resources :addresses

  root 'welcome#index'

  
end

app/models/acknowledgement.rb
class Acknowledgement < ActiveRecord::Base
end

app/controllers/acknowledgements_controller.rb
class AcknowledgementsController < ApplicationController
  before_action :set_acknowledgement, only: [:show, :edit, :update, :destroy]

  # GET /acknowledgements
  # GET /acknowledgements.json
  def index
    @acknowledgements = Acknowledgement.all
  end

  # GET /acknowledgements/1
  # GET /acknowledgements/1.json
  def show
  end

  # GET /acknowledgements/new
  def new
    @acknowledgement = Acknowledgement.new
  end

  # GET /acknowledgements/1/edit
  def edit
  end

  # POST /acknowledgements
  # POST /acknowledgements.json
  def create
    @acknowledgement = Acknowledgement.new(acknowledgement_params)

    respond_to do |format|
      if @acknowledgement.save
        format.html { redirect_to @acknowledgement, notice: 'Acknowledgement was successfully created.' }
        format.json { render :show, status: :created, location: @acknowledgement }
      else
        format.html { render :new }
        format.json { render json: @acknowledgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acknowledgements/1
  # PATCH/PUT /acknowledgements/1.json
  def update
    respond_to do |format|
      if @acknowledgement.update(acknowledgement_params)
        format.html { redirect_to @acknowledgement, notice: 'Acknowledgement was successfully updated.' }
        format.json { render :show, status: :ok, location: @acknowledgement }
      else
        format.html { render :edit }
        format.json { render json: @acknowledgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acknowledgements/1
  # DELETE /acknowledgements/1.json
  def destroy
    @acknowledgement.destroy
    respond_to do |format|
      format.html { redirect_to acknowledgements_url, notice: 'Acknowledgement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acknowledgement
      @acknowledgement = Acknowledgement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acknowledgement_params
      params.require(:acknowledgement).permit(:name, :url, :subject, :comments)
    end
end

app/helpers/acknowledgements_helper.rb
module AcknowledgementsHelper
end

app/views/acknowledgements/_form.html.erb
<%= form_for(@acknowledgement) do |f| %>
  <% if @acknowledgement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acknowledgement.errors.count, "error") %> prohibited this acknowledgement from being saved:</h2>

      <ul>
      <% @acknowledgement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acknowledgements/edit.html.erb
<h1>Editing Acknowledgement</h1>

<%= render 'form' %>

<%= link_to 'Show', @acknowledgement %> |
<%= link_to 'Back', acknowledgements_path %>

app/views/acknowledgements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acknowledgements</h1>
<h2>References and sources, and inspirations.</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Subject</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acknowledgements.each do |acknowledgement| %>
      <tr>
        <td><%= acknowledgement.name %></td>
        <td><%= acknowledgement.url %></td>
        <td><%= acknowledgement.subject %></td>
        <td><%= acknowledgement.comments %></td>
        <td><%= link_to 'Show', acknowledgement %></td>
        <td><%= link_to 'Edit', edit_acknowledgement_path(acknowledgement) %></td>
        <td><%= link_to 'Destroy', acknowledgement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acknowledgement', new_acknowledgement_path %>

app/views/acknowledgements/new.html.erb
<h1>New Acknowledgement</h1>

<%= render 'form' %>

<%= link_to 'Back', acknowledgements_path %>

app/views/acknowledgements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @acknowledgement.name %>
</p>

<p>
  <strong>URL:</strong>
  <%= @acknowledgement.url %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @acknowledgement.subject %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @acknowledgement.comments %>
</p>

<%= link_to 'Edit', edit_acknowledgement_path(@acknowledgement) %> |
<%= link_to 'Back', acknowledgements_path %>