config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :acknowledgements
  get 'welcome/index'

  resources :people
  resources :addresses

  root 'welcome#index'

  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.order(sort_column + " " + sort_direction)
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end
  
  # Get coordinates/ GVS addition
  def coords
    # the following line is a minor change from a tutorial. Don't really know what it means
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:address, :city, :state, :longitude, :latitude, :extant, :current_description, :notes)
    end
    
    def sort_column
      Address.column_names.include?(params[:sort]) ? params[:sort] : "address"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :extant, "Is the building from the turn of the century?" %>
    <%= f.check_box :extant %>
  </div>
  <div class="field">
    <%= f.label :current_description %>
    <%= f.text_field :current_description %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>
  <!-- <div class="field">
    <%= f.label :Geometry %>
    <%= f.text_field :geom %>
  </div> -->
  <div class="actions">
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/addresses/coords.html.erb
<h1>Finding coordinates for an address</h1>
<h3>Using Mapbox</h3>
 
<%= form_for :address, url: address_path(@address), method: :patch do |f| %>
 
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@address.errors.count, "error") %> prohibited
        this address from being saved:
      </h2>
      <ul>
        <% @address.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  # <p>
  #   <%= f.label :title %><br>
  #   <%= f.text_field :title %>
  # </p>
  #
  # <p>
  #   <%= f.label :text %><br>
  #   <%= f.text_area :text %>
  # </p>
 
  <%= render 'form' %>

  <%= link_to 'Show', @address %> |
  <%= link_to 'Back', addresses_path %>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', addresses_path %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<div class="row">
  <div class= "col-md-6 col-md-offset-3">

    <%= render 'form' %>

    <%= link_to 'Show', @address %> |
    <%= link_to 'To address list', addresses_path %>
    
  </div>
</div>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table class="addresses pretty">
  <thead>
    <tr>

      <th><%= sortable "address" %></th>
      <th><%= sortable "city" %></th>
      <th><%= sortable "longitude" %></th>
      <th><%= sortable "latitude" %></th>
      <th><%= sortable "extant" %></th>
      <th><%= sortable "current_description", "Current" %></th>
      <th><%= sortable "notes" %></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.address %></td>
        <td><%= address.city %></td>
        <td><%= address.longitude %></td>
        <td><%= address.latitude %></td>
        <td><%= address.extant %></td>
        <td><%= address.current_description %></td>
        <td><%= address.notes %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <% if false %>
           <td><%= link_to 'Add Coords', edit_coord_path(address) %></td> %>
         <% end %>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path , class: "btn btn-primary"%>
<%= render 'layouts/footer' %>

app/views/addresses/new.html.erb
<h1>New Address</h1>
<div class="row">
  <div class= "col-md-6 col-md-offset-3">

    <%= render 'form' %>

    <%= link_to 'Address list', addresses_path %>  |

    <%= link_to 'People list', people_path %> | 

    <%= link_to 'Main Page', root_path  %>
  </div>
</div>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @address.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @address.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @address.latitude %>
</p>

<p>
  <strong>Extant:</strong>
  <%= @address.extant %>
</p>

<p>
  <strong>Current:</strong>
  <%= @address.current_description %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @address.notes %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'To address list', addresses_path %>