config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :acknowledgements
  get 'welcome/index'

  resources :people
  resources :addresses

  root 'welcome#index'

  
end

app/models/year.rb
class Year < ActiveRecord::Base
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: [:show, :edit, :update, :destroy]

  # GET /years
  # GET /years.json
  def index
    @years = Year.all
  end

  # GET /years/1
  # GET /years/1.json
  def show
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years
  # POST /years.json
  def create
    @year = Year.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to @year, notice: 'Year was successfully created.' }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1
  # PATCH/PUT /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to @year, notice: 'Year was successfully updated.' }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1
  # DELETE /years/1.json
  def destroy
    @year.destroy
    respond_to do |format|
      format.html { redirect_to years_url, notice: 'Year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      @year = Year.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_params
      params.require(:year).permit(:year_date)
    end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/_form.html.erb
<%= form_for(@year) do |f| %>
  <% if @year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
      <% @year.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year_date %><br>
    <%= f.date_select :year_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing Year</h1>

<%= render 'form' %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Years</h1>

<table>
  <thead>
    <tr>
      <th>Year date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @years.each do |year| %>
      <tr>
        <td><%= year.year_date %></td>
        <td><%= link_to 'Show', year %></td>
        <td><%= link_to 'Edit', edit_year_path(year) %></td>
        <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year', new_year_path %>

app/views/years/new.html.erb
<h1>New Year</h1>

<%= render 'form' %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year date:</strong>
  <%= @year.year_date %>
</p>

<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>